# TCL File Generated by Component Editor 25.1
# Sat Apr 25 15:33:11 CDT 2026
# DO NOT MODIFY


# 
# ooo_p "Ozone Processor" v1.0
# Rishab, Sean, Sid, Nathan, Brayden, & Max 2026.04.25.15:33:11
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ooo_p
# 
set_module_property DESCRIPTION ""
set_module_property NAME ooo_p
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Rishab, Sean, Sid, Nathan, Brayden, & Max"
set_module_property DISPLAY_NAME "Ozone Processor"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ozone_quartus_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ozone_quartus_top.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/cpu/ozone/verilator/ozone_quartus_top.sv"
add_fileset_file l1_cache.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/l1_cache.sv"
add_fileset_file l2.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/l2.sv"
add_fileset_file lsq.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/lsq.sv"
add_fileset_file mem_pkg.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/mem_pkg.sv"
add_fileset_file memsys.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/memsys.sv"
add_fileset_file ooo_pkg.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/ooo_pkg.sv"
add_fileset_file tlb.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/tlb.sv"
add_fileset_file Top.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/cpu/ozone/verilator/Top.sv"
add_fileset_file ozone_cdb.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/cpu/ozone/verilator/ozone_cdb.sv"
add_fileset_file ozone_pkg.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/cpu/ozone/verilator/ozone_pkg.sv"
add_fileset_file types.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/cpu/ozone/verilator/types.sv"
add_fileset_file ozone_dispatch.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/cpu/ozone/verilator/backend/ozone_dispatch.sv"
add_fileset_file ozone_dtlb.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/cpu/ozone/verilator/backend/ozone_dtlb.sv"
add_fileset_file ozone_regstate.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/cpu/ozone/verilator/backend/ozone_regstate.sv"
add_fileset_file ozone_rob.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/cpu/ozone/verilator/backend/ozone_rob.sv"
add_fileset_file ozone_bpred.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/cpu/ozone/verilator/frontend/ozone_bpred.sv"
add_fileset_file ozone_btb.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/cpu/ozone/verilator/frontend/ozone_btb.sv"
add_fileset_file ozone_decode.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/cpu/ozone/verilator/frontend/ozone_decode.sv"
add_fileset_file ozone_itlb.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/cpu/ozone/verilator/frontend/ozone_itlb.sv"
add_fileset_file ozone_adder.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/cpu/ozone/verilator/fu/ozone_adder.sv"
add_fileset_file ozone_agu.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/cpu/ozone/verilator/fu/ozone_agu.sv"
add_fileset_file ozone_logic.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/cpu/ozone/verilator/fu/ozone_logic.sv"
add_fileset_file ozone_shifter.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/cpu/ozone/verilator/fu/ozone_shifter.sv"
add_fileset_file fpnew_pkg.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/cpu/ozone/verilator/fu/fpu/fpnew_pkg.sv"
add_fileset_file fpnew_cast_multi.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/cpu/ozone/verilator/fu/fpu/fpnew_cast_multi.sv"
add_fileset_file fpnew_classifier.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/cpu/ozone/verilator/fu/fpu/fpnew_classifier.sv"
add_fileset_file fpnew_divsqrt_multi.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/cpu/ozone/verilator/fu/fpu/fpnew_divsqrt_multi.sv"
add_fileset_file fpnew_divsqrt_th_32.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/cpu/ozone/verilator/fu/fpu/fpnew_divsqrt_th_32.sv"
add_fileset_file fpnew_divsqrt_th_64_multi.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/cpu/ozone/verilator/fu/fpu/fpnew_divsqrt_th_64_multi.sv"
add_fileset_file fpnew_fma.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/cpu/ozone/verilator/fu/fpu/fpnew_fma.sv"
add_fileset_file fpnew_fma_multi.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/cpu/ozone/verilator/fu/fpu/fpnew_fma_multi.sv"
add_fileset_file fpnew_noncomp.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/cpu/ozone/verilator/fu/fpu/fpnew_noncomp.sv"
add_fileset_file fpnew_opgroup_block.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/cpu/ozone/verilator/fu/fpu/fpnew_opgroup_block.sv"
add_fileset_file fpnew_opgroup_fmt_slice.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/cpu/ozone/verilator/fu/fpu/fpnew_opgroup_fmt_slice.sv"
add_fileset_file fpnew_opgroup_multifmt_slice.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/cpu/ozone/verilator/fu/fpu/fpnew_opgroup_multifmt_slice.sv"
add_fileset_file fpnew_rounding.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/cpu/ozone/verilator/fu/fpu/fpnew_rounding.sv"
add_fileset_file fpnew_top.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/cpu/ozone/verilator/fu/fpu/fpnew_top.sv"
add_fileset_file fpnew_top_core.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/cpu/ozone/verilator/fu/fpu/fpnew_top_core.sv"
add_fileset_file lzc.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/cpu/ozone/verilator/fu/fpu/lzc.sv"
add_fileset_file rr_arb_tree.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/cpu/ozone/verilator/fu/fpu/rr_arb_tree.sv"
add_fileset_file barrel_shifter.sv SYSTEM_VERILOG PATH "../../../../aca - files/memsubsys/memlab/cpu/ozone/verilator/fu/barrel_shifter.sv"


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

